[2025-05-27T19:03:48.002+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-27T19:03:36.296945+00:00 [queued]>
[2025-05-27T19:03:48.007+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-27T19:03:36.296945+00:00 [queued]>
[2025-05-27T19:03:48.007+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-27T19:03:48.014+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): data_quality_checks> on 2025-05-27 19:03:36.296945+00:00
[2025-05-27T19:03:48.020+0000] {standard_task_runner.py:57} INFO - Started process 907 to run task
[2025-05-27T19:03:48.027+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'walmart_etl_dag', 'data_quality_checks', 'manual__2025-05-27T19:03:36.296945+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/walmart_etl_dag.py', '--cfg-path', '/tmp/tmpllv6nrgf']
[2025-05-27T19:03:48.031+0000] {standard_task_runner.py:85} INFO - Job 283: Subtask data_quality_checks
[2025-05-27T19:03:48.102+0000] {task_command.py:416} INFO - Running <TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-27T19:03:36.296945+00:00 [running]> on host d80f98a6628f
[2025-05-27T19:03:48.803+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='walmart_etl_dag' AIRFLOW_CTX_TASK_ID='data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T19:03:36.296945+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-27T19:03:36.296945+00:00'
[2025-05-27T19:03:48.812+0000] {logging_mixin.py:154} INFO - Found 1314 records in tgt_dim_product
[2025-05-27T19:03:48.813+0000] {logging_mixin.py:154} INFO - Found 1636 records in tgt_dim_store
[2025-05-27T19:03:48.816+0000] {logging_mixin.py:154} INFO - Found 8399 records in tgt_fact_sales
[2025-05-27T19:03:48.816+0000] {logging_mixin.py:154} INFO - WARNING: No data in tgt_fact_inventory
[2025-05-27T19:03:48.817+0000] {logging_mixin.py:154} INFO - WARNING: No data in tgt_fact_returns
[2025-05-27T19:03:48.817+0000] {python.py:194} INFO - Done. Returned value was: Data quality checks completed. Products: 1314, Stores: 1636, Sales: 8399, Inventory: 0, Returns: 0
[2025-05-27T19:03:48.832+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=walmart_etl_dag, task_id=data_quality_checks, execution_date=20250527T190336, start_date=20250527T190348, end_date=20250527T190348
[2025-05-27T19:03:48.869+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-27T19:03:48.912+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
